
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class AWSConfig
{

    public AWSConfig()
    {

        this.AWSResources = new HashSet<AWSResource>();

        this.GNOrganizations = new HashSet<GNOrganization>();

        this.AWSComputeEnvironments = new HashSet<AWSComputeEnvironment>();

    }


    public System.Guid Id { get; set; }

    public string AWSAccessKeyId { get; set; }

    public string AWSSecretAccessKey { get; set; }

    public string AWSRegionSystemName { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<AWSResource> AWSResources { get; set; }

    public virtual AWSRegion AWSRegion { get; set; }

    public virtual ICollection<GNOrganization> GNOrganizations { get; set; }

    public virtual ICollection<AWSComputeEnvironment> AWSComputeEnvironments { get; set; }

}

}
