
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class AWSResource
{

    public System.Guid Id { get; set; }

    public string ARN { get; set; }

    public System.Guid AWSConfigId { get; set; }

    public int AWSResourceTypeId { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual AWSConfig AWSConfig { get; set; }

    public virtual AWSResourceType AWSResourceType { get; set; }

}

}
