
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNAccountThreshold
{

    public System.Guid Id { get; set; }

    public double ThresholdAmount { get; set; }

    public int Rank { get; set; }

    public string ThresholdType { get; set; }

    public int ThresholdInterval { get; set; }

    public System.Guid GNAccountId { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNAccount Account { get; set; }

}

}
