
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNAccount
{

    public GNAccount()
    {

        this.BillingMode = "C";

        this.PaymentMethods = new HashSet<GNPaymentMethod>();

        this.Invoices = new HashSet<GNInvoice>();

        this.AccountProductSubscriptions = new HashSet<GNAccountProductSubscription>();

        this.PurchaseOrders = new HashSet<GNPurchaseOrder>();

        this.AccountThresholds = new HashSet<GNAccountThreshold>();

    }


    public System.Guid Id { get; set; }

    public double TotalAmountPaid { get; set; }

    public double TotalAmountOwed { get; set; }

    public string DefaultDiscountType { get; set; }

    public double DefaultDiscountAmount { get; set; }

    public string BillingMode { get; set; }

    public double MaxBalanceAllowed { get; set; }

    public double AvailableCredits { get; set; }

    public bool ValidBillingAgreementRequired { get; set; }

    public int GNAccountTypeId { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNContact AccountOwner { get; set; }

    public virtual GNContact MailingContact { get; set; }

    public virtual GNContact BillingContact { get; set; }

    public virtual ICollection<GNPaymentMethod> PaymentMethods { get; set; }

    public virtual ICollection<GNInvoice> Invoices { get; set; }

    public virtual GNOrganization Organization { get; set; }

    public virtual ICollection<GNAccountProductSubscription> AccountProductSubscriptions { get; set; }

    public virtual GNAccountType AccountType { get; set; }

    public virtual ICollection<GNPurchaseOrder> PurchaseOrders { get; set; }

    public virtual ICollection<GNAccountThreshold> AccountThresholds { get; set; }

}

}
