
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNAccountType
{

    public GNAccountType()
    {

        this.Accounts = new HashSet<GNAccount>();

        this.Products = new HashSet<GNProduct>();

        this.GNBillingAccounts = new HashSet<GNBillingAccount>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNAccount> Accounts { get; set; }

    public virtual ICollection<GNProduct> Products { get; set; }

    public virtual ICollection<GNBillingAccount> GNBillingAccounts { get; set; }

}

}
