
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNAnalysisRequestGroupComparison
{

    public System.Guid Id { get; set; }

    public System.Guid GNAnalysisRequestId { get; set; }

    public System.Guid GNAnalysisRequestControlGroupId { get; set; }

    public System.Guid GNAnalysisRequestComparisonGroupId { get; set; }



    public virtual GNAnalysisRequestGroup GNAnalysisRequestControlGroup { get; set; }

    public virtual GNAnalysisRequestGroup GNAnalysisRequestComparisonGroup { get; set; }

    public virtual GNAnalysisRequest GNAnalysisRequest { get; set; }

}

}
