
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNAnalysisResult
{

    public GNAnalysisResult()
    {

        this.ResultFiles = new HashSet<GNCloudFile>();

        this.AnalysisStatus = new HashSet<GNAnalysisStatus>();

    }


    public System.Guid Id { get; set; }

    public bool Success { get; set; }

    public System.DateTime AnalysisStartDateTime { get; set; }

    public System.DateTime AnalysisEndDateTime { get; set; }

    public string AWSRegionSystemName { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNCloudFile> ResultFiles { get; set; }

    public virtual AWSRegion AWSRegion { get; set; }

    public virtual ICollection<GNAnalysisStatus> AnalysisStatus { get; set; }

    public virtual GNAnalysisRequest AnalysisRequest { get; set; }

}

}
