
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNAnalysisRequestGNSample
{

    public System.Guid GNAnalysisRequestId { get; set; }

    public System.Guid GNSampleId { get; set; }

    public string AffectedIndicator { get; set; }

    public string TargetIndicator { get; set; }



    public virtual GNSample GNSample { get; set; }

    public virtual GNAnalysisRequest GNAnalysisRequest { get; set; }

}

}
