
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNBillingAccount
{

    public GNBillingAccount()
    {

        this.BillingMode = "C";

        this.GNBillingPurchaseOrders = new HashSet<GNBillingPurchaseOrder>();

        this.GNBillingPaymentMethods = new HashSet<GNBillingPaymentMethod>();

        this.GNBillingInvoices = new HashSet<GNBillingInvoice>();

    }


    public System.Guid Id { get; set; }

    public int GNAccountTypeId { get; set; }

    public System.Guid GNOrganizationId { get; set; }

    public string BillingMode { get; set; }

    public double MaxBalanceAllowed { get; set; }

    public double TotalAmountOwed { get; set; }

    public double AvailableCredits { get; set; }

    public bool ValidBillingAgreementRequired { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }



    public virtual ICollection<GNBillingPurchaseOrder> GNBillingPurchaseOrders { get; set; }

    public virtual ICollection<GNBillingPaymentMethod> GNBillingPaymentMethods { get; set; }

    public virtual GNOrganization GNOrganization { get; set; }

    public virtual GNAccountType GNAccountType { get; set; }

    public virtual GNContact GNBillingContact { get; set; }

    public virtual GNContact GNMailingContact { get; set; }

    public virtual ICollection<GNBillingInvoice> GNBillingInvoices { get; set; }

}

}
