
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNBillingInvoice
{

    public GNBillingInvoice()
    {

        this.GNBillingPurchaseOrderInvoices = new HashSet<GNBillingPurchaseOrderInvoice>();

        this.GNBillingInvoiceDetails = new HashSet<GNBillingInvoiceDetail>();

        this.GNBillingPaymentInvoices = new HashSet<GNBillingPaymentInvoice>();

    }


    public System.Guid Id { get; set; }

    public System.Guid GNBillingAccountId { get; set; }

    public string ExternalInvoiceNum { get; set; }

    public System.DateTime InvoiceStartDate { get; set; }

    public System.DateTime InvoiceEndDate { get; set; }

    public string Status { get; set; }

    public double TotalDiscountAmount { get; set; }

    public double Total { get; set; }

    public double TotalPaid { get; set; }

    public int NetTerms { get; set; }

    public string InvoiceCycle { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }



    public virtual ICollection<GNBillingPurchaseOrderInvoice> GNBillingPurchaseOrderInvoices { get; set; }

    public virtual ICollection<GNBillingInvoiceDetail> GNBillingInvoiceDetails { get; set; }

    public virtual GNBillingAccount GNBillingAccount { get; set; }

    public virtual ICollection<GNBillingPaymentInvoice> GNBillingPaymentInvoices { get; set; }

}

}
