
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNBillingPaymentInvoice
{

    public System.Guid Id { get; set; }

    public double TotalApplied { get; set; }

    public System.Guid GNBillingInvoiceId { get; set; }

    public System.Guid GNBillingPaymentId { get; set; }



    public virtual GNBillingInvoice GNBillingInvoice { get; set; }

    public virtual GNBillingPayment GNBillingPayment { get; set; }

}

}
