
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNBillingInvoiceDetail
{

    public GNBillingInvoiceDetail()
    {

        this.GNBillingTransactions = new HashSet<GNBillingTransaction>();

    }


    public System.Guid Id { get; set; }

    public System.Guid GNBillingInvoiceId { get; set; }

    public string Description { get; set; }

    public double UnitCost { get; set; }

    public double UnitPrice { get; set; }

    public double Quantity { get; set; }

    public string DiscountType { get; set; }

    public double DiscountAmount { get; set; }

    public double SubTotal { get; set; }

    public double Total { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNBillingInvoice GNBillingInvoice { get; set; }

    public virtual ICollection<GNBillingTransaction> GNBillingTransactions { get; set; }

}

}
