
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNBulkImportGroupStaging
{

    public long ROW_IDX { get; set; }

    public string ANALYSIS_NAME { get; set; }

    public string CONTROL_GROUP_NAME { get; set; }

    public string COMPARISON_GROUP_NAME { get; set; }

    public System.Guid GNBulkImportStatusId { get; set; }



    public virtual GNBulkImportStatus GNBulkImportStatu { get; set; }

}

}
