
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNBulkImportStatus
{

    public GNBulkImportStatus()
    {

        this.TotalRecordCount = 0;

        this.ImportedRecordCount = 0;

        this.FailedRecordCount = 0;

        this.DuplicateRecordCount = 0;

        this.TeamsCreatedCount = 0;

        this.ProjectsCreatedCount = 0;

        this.AnalysesCreatedCount = 0;

        this.SamplesCreatedCount = 0;

        this.FilesCreatedCount = 0;

        this.BulkImportLogs = new HashSet<GNBulkImportLog>();

        this.GNBulkImportStagings = new HashSet<GNBulkImportStaging>();

        this.GNBulkImportGroupStagings = new HashSet<GNBulkImportGroupStaging>();

    }


    public System.Guid Id { get; set; }

    public string FileURIType { get; set; }

    public string FileURI { get; set; }

    public string FileExtension { get; set; }

    public string FileMimeType { get; set; }

    public long TotalRecordCount { get; set; }

    public long ImportedRecordCount { get; set; }

    public long FailedRecordCount { get; set; }

    public long DuplicateRecordCount { get; set; }

    public long TeamsCreatedCount { get; set; }

    public long ProjectsCreatedCount { get; set; }

    public long AnalysesCreatedCount { get; set; }

    public long SamplesCreatedCount { get; set; }

    public long FilesCreatedCount { get; set; }

    public Nullable<System.DateTime> ImportStartDateTime { get; set; }

    public Nullable<System.DateTime> ImportEndDateTime { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNBulkImportLog> BulkImportLogs { get; set; }

    public virtual ICollection<GNBulkImportStaging> GNBulkImportStagings { get; set; }

    public virtual ICollection<GNBulkImportGroupStaging> GNBulkImportGroupStagings { get; set; }

}

}
