
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNBulkImportStaging
{

    public long ROW_IDX { get; set; }

    public string TEAM_NAME { get; set; }

    public string PROJECT_NAME { get; set; }

    public string ANALYSIS_NAME { get; set; }

    public string ANALYSIS_TYPE { get; set; }

    public string ANALYSIS_ADAPTOR { get; set; }

    public string ANALYSIS_GROUP_NAME { get; set; }

    public string SAMPLE_NAME { get; set; }

    public string SAMPLE_TYPE { get; set; }

    public string SAMPLE_GENDER { get; set; }

    public string SAMPLE_READ_TYPE { get; set; }

    public string SAMPLE_QUALIFIER { get; set; }

    public string FILE_BUCKET { get; set; }

    public string FILE_KEY { get; set; }

    public string FILE_SIZE { get; set; }

    public string AUTO_START { get; set; }

    public System.Guid GNBulkImportStatusId { get; set; }



    public virtual GNBulkImportStatus GNBulkImportStatus { get; set; }

}

}
