
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNContact
{

    public GNContact()
    {

        this.GNContactRoles = new HashSet<GNContactRole>();

        this.GNNotificationTopicSubscribers = new HashSet<GNNotificationTopicSubscriber>();

        this.GNBillingAccountsBillingContacts = new HashSet<GNBillingAccount>();

        this.GNBillingAccountsMailingContacts = new HashSet<GNBillingAccount>();

    }


    public System.Guid Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Title { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string StreetAddress1 { get; set; }

    public string StreetAddress2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public Nullable<bool> IsInviteAccepted { get; set; }

    public Nullable<System.DateTime> TermsAcceptDateTime { get; set; }

    public Nullable<System.DateTime> PrivacyPolicyAcceptDateTime { get; set; }

    public string AspNetUserId { get; set; }

    public System.Guid GNOrganizationId { get; set; }

    public Nullable<bool> IsSubscribedForNewsletters { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNOrganization GNOrganization { get; set; }

    public virtual ICollection<GNContactRole> GNContactRoles { get; set; }

    public virtual ICollection<GNNotificationTopicSubscriber> GNNotificationTopicSubscribers { get; set; }

    public virtual ICollection<GNBillingAccount> GNBillingAccountsBillingContacts { get; set; }

    public virtual ICollection<GNBillingAccount> GNBillingAccountsMailingContacts { get; set; }

}

}
