

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class GNEntityModelContainer : DbContext
{
    public GNEntityModelContainer()
        : base("name=GNEntityModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<GNAccount> GNAccounts { get; set; }

    public virtual DbSet<GNAnalysisRequest> GNAnalysisRequests { get; set; }

    public virtual DbSet<GNAnalysisResult> GNAnalysisResults { get; set; }

    public virtual DbSet<GNCloudFileCategory> GNCloudFileCategories { get; set; }

    public virtual DbSet<GNCloudFile> GNCloudFiles { get; set; }

    public virtual DbSet<GNInvoiceDetail> GNInvoiceDetails { get; set; }

    public virtual DbSet<GNInvoice> GNInvoices { get; set; }

    public virtual DbSet<GNPaymentMethod> GNPaymentMethods { get; set; }

    public virtual DbSet<GNPayment> GNPayments { get; set; }

    public virtual DbSet<GNTransaction> GNTransactions { get; set; }

    public virtual DbSet<GNTransactionType> GNTransactionTypes { get; set; }

    public virtual DbSet<GNOrganization> GNOrganizations { get; set; }

    public virtual DbSet<GNTeam> GNTeams { get; set; }

    public virtual DbSet<GNContact> GNContacts { get; set; }

    public virtual DbSet<GNTeamMember> GNTeamMembers { get; set; }

    public virtual DbSet<GNProject> GNProjects { get; set; }

    public virtual DbSet<GNSample> GNSamples { get; set; }

    public virtual DbSet<GNAnalysisType> GNAnalysisTypes { get; set; }

    public virtual DbSet<GNTag> GNTags { get; set; }

    public virtual DbSet<GNEntityTag> GNEntityTags { get; set; }

    public virtual DbSet<GNProduct> GNProducts { get; set; }

    public virtual DbSet<GNProductType> GNProductTypes { get; set; }

    public virtual DbSet<GNEntityType> GNEntityTypes { get; set; }

    public virtual DbSet<AWSConfig> AWSConfigs { get; set; }

    public virtual DbSet<AWSResource> AWSResources { get; set; }

    public virtual DbSet<AWSResourceType> AWSResourceTypes { get; set; }

    public virtual DbSet<GNSampleType> GNSampleTypes { get; set; }

    public virtual DbSet<AWSRegion> AWSRegions { get; set; }

    public virtual DbSet<GNAnalysisStatus> GNAnalysisStatus { get; set; }

    public virtual DbSet<GNContactRole> GNContactRoles { get; set; }

    public virtual DbSet<GNEntityAudit> GNEntityAudits { get; set; }

    public virtual DbSet<GNEntityAuditType> GNEntityAuditTypes { get; set; }

    public virtual DbSet<GNSampleRelationship> GNSampleRelationships { get; set; }

    public virtual DbSet<GNSampleRelationshipType> GNSampleRelationshipTypes { get; set; }

    public virtual DbSet<GNLog> GNLogs { get; set; }

    public virtual DbSet<GNInviteCode> GNInviteCodes { get; set; }

    public virtual DbSet<GNPaymentMethodType> GNPaymentMethodTypes { get; set; }

    public virtual DbSet<GNAccountProductSubscription> GNAccountProductSubscriptions { get; set; }

    public virtual DbSet<GNNotificationTopic> GNNotificationTopics { get; set; }

    public virtual DbSet<GNNotificationLog> GNNotificationLogs { get; set; }

    public virtual DbSet<GNAccountType> GNAccountTypes { get; set; }

    public virtual DbSet<GNPurchaseOrder> GNPurchaseOrders { get; set; }

    public virtual DbSet<GNAccountThreshold> GNAccountThresholds { get; set; }

    public virtual DbSet<GNAnalysisRequestGNSample> GNAnalysisRequestGNSamples { get; set; }

    public virtual DbSet<GNAnalysisSampleAffectedIndicator> GNAnalysisSampleAffectedIndicators { get; set; }

    public virtual DbSet<GNPurchaseOrderGNInvoice> GNPurchaseOrderGNInvoice { get; set; }

    public virtual DbSet<GNNotificationTopicSubscriber> GNNotificationTopicSubscribers { get; set; }

    public virtual DbSet<GNNotificationTopicAddressee> GNNotificationTopicAddressees { get; set; }

    public virtual DbSet<GNNotificationSender> GNNotificationSenders { get; set; }

    public virtual DbSet<GNSampleRelationshipTypeMapping> GNSampleRelationshipTypeMappings { get; set; }

    public virtual DbSet<GNBulkImportStatus> GNBulkImportStatus { get; set; }

    public virtual DbSet<GNBulkImportLog> GNBulkImportLogs { get; set; }

    public virtual DbSet<GNBulkImportStaging> GNBulkImportStaging { get; set; }

    public virtual DbSet<GNSettingsTemplate> GNSettingsTemplates { get; set; }

    public virtual DbSet<GNSettingsTemplateConfig> GNSettingsTemplateConfigs { get; set; }

    public virtual DbSet<GNSettingsTemplateField> GNSettingsTemplateFields { get; set; }

    public virtual DbSet<AWSComputeEnvironment> AWSComputeEnvironments { get; set; }

    public virtual DbSet<GNNotificationSuppressionList> GNNotificationSuppressionLists { get; set; }

    public virtual DbSet<GNTemplate> GNTemplates { get; set; }

    public virtual DbSet<GNTemplateGene> GNTemplateGenes { get; set; }

    public virtual DbSet<GNAnalysisRequestGNTemplate> GNAnalysisRequestGNTemplates { get; set; }

    public virtual DbSet<GNGene> GNGenes { get; set; }

    public virtual DbSet<GNSampleQualifier> GNSampleQualifiers { get; set; }

    public virtual DbSet<GNAnalysisRequestType> GNAnalysisRequestTypes { get; set; }

    public virtual DbSet<GNSampleQualifierGroup> GNSampleQualifierGroups { get; set; }

    public virtual DbSet<GNSharedPurchaseOrderOrganization> GNSharedPurchaseOrderOrganizations { get; set; }

    public virtual DbSet<GNAnalysisRequestGroup> GNAnalysisRequestGroups { get; set; }

    public virtual DbSet<GNAnalysisRequestGroupComparison> GNAnalysisRequestGroupComparisons { get; set; }

    public virtual DbSet<GNAnalysisAdaptor> GNAnalysisAdaptors { get; set; }

    public virtual DbSet<GNBillingAccount> GNBillingAccounts { get; set; }

    public virtual DbSet<GNBillingInvoice> GNBillingInvoices { get; set; }

    public virtual DbSet<GNBillingInvoiceDetail> GNBillingInvoiceDetails { get; set; }

    public virtual DbSet<GNBillingPaymentMethod> GNBillingPaymentMethods { get; set; }

    public virtual DbSet<GNBillingPurchaseOrder> GNBillingPurchaseOrders { get; set; }

    public virtual DbSet<GNBillingPurchaseOrderInvoice> GNBillingPurchaseOrderInvoices { get; set; }

    public virtual DbSet<GNBillingPaymentInvoice> GNBillingPaymentInvoices { get; set; }

    public virtual DbSet<GNBillingPayment> GNBillingPayments { get; set; }

    public virtual DbSet<GNBillingTransaction> GNBillingTransactions { get; set; }

    public virtual DbSet<GNBulkImportGroupStaging> GNBulkImportGroupStagings { get; set; }

    public virtual DbSet<GNSampleStatus> GNSampleStatus { get; set; }

    public virtual DbSet<GNNewSampleBatch> GNNewSampleBatches { get; set; }

    public virtual DbSet<GNNewSampleBatchStatus> GNNewSampleBatchStatus { get; set; }

    public virtual DbSet<GNNewSampleBatchSamples> GNNewSampleBatchSamples { get; set; }

    public virtual DbSet<GNSequencerJob> GNSequencerJobs { get; set; }

    public virtual DbSet<GNReplicate> GNReplicates { get; set; }

}

}

