
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNEntityType
{

    public GNEntityType()
    {

        this.GNEntityTags = new HashSet<GNEntityTag>();

        this.GNEntityAudits = new HashSet<GNEntityAudit>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNEntityTag> GNEntityTags { get; set; }

    public virtual ICollection<GNEntityAudit> GNEntityAudits { get; set; }

}

}
