
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNGene
{

    public GNGene()
    {

        this.GNTemplateGenes = new HashSet<GNTemplateGene>();

    }


    public long Id { get; set; }

    public string GeneCode { get; set; }

    public string Chromosome { get; set; }

    public string CytoBand { get; set; }

    public string Isoform { get; set; }

    public System.Guid CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNTemplateGene> GNTemplateGenes { get; set; }

}

}
