
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNInvoice
{

    public GNInvoice()
    {

        this.InvoiceDetails = new HashSet<GNInvoiceDetail>();

        this.Payments = new HashSet<GNPayment>();

        this.PurchaseOrderInvoices = new HashSet<GNPurchaseOrderGNInvoice>();

        this.GNSharedPurchaseOrderOrganizations = new HashSet<GNSharedPurchaseOrderOrganization>();

    }


    public System.Guid Id { get; set; }

    public string ExternalInvoiceNum { get; set; }

    public System.DateTime InvoiceStartDate { get; set; }

    public System.DateTime InvoiceEndDate { get; set; }

    public string Status { get; set; }

    public double TotalDiscountAmount { get; set; }

    public double SubTotal { get; set; }

    public double Total { get; set; }

    public int NetTerms { get; set; }

    public System.Guid GNAccountId { get; set; }

    public string InvoiceCycle { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNAccount Account { get; set; }

    public virtual ICollection<GNInvoiceDetail> InvoiceDetails { get; set; }

    public virtual ICollection<GNPayment> Payments { get; set; }

    public virtual ICollection<GNPurchaseOrderGNInvoice> PurchaseOrderInvoices { get; set; }

    public virtual ICollection<GNSharedPurchaseOrderOrganization> GNSharedPurchaseOrderOrganizations { get; set; }

}

}
