
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNInviteCode
{

    public GNInviteCode()
    {

        this.FreeCreditAllowance = 0D;

    }


    public string InviteCode { get; set; }

    public string Description { get; set; }

    public double FreeCreditAllowance { get; set; }

    public int UseCount { get; set; }

    public Nullable<int> UseMaxAllowed { get; set; }

    public Nullable<System.DateTime> ExpireDate { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

}

}
