
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNNewSampleBatchStatus
{

    public GNNewSampleBatchStatus()
    {

        this.Status = "\'PROCESSING\'";

    }


    public System.Guid Id { get; set; }

    public System.Guid GNNewSampleBatchId { get; set; }

    public string Repository { get; set; }

    public string Status { get; set; }

    public int PercentComplete { get; set; }

    public bool IsError { get; set; }

    public string Message { get; set; }

    public string FilesBucket { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNNewSampleBatch GNNewSampleBatch { get; set; }

}

}
