
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNNewSampleBatchSamples
{

    public GNNewSampleBatchSamples()
    {

        this.Gender = "\'U\'";

        this.RelationId = "\'U\'";

    }


    public System.Guid Id { get; set; }

    public System.Guid GNNewSampleBatchId { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public string FamilyId { get; set; }

    public string RelationId { get; set; }

    public string Affected { get; set; }

    public string Proband { get; set; }

    public string AnalysisName { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNNewSampleBatch GNNewSampleBatch { get; set; }

    public virtual GNSample GNSample { get; set; }

}

}
