
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNNotificationTopicSubscriber
{

    public int GNNotificationTopicId { get; set; }

    public System.Guid GNContactId { get; set; }

    public string AddresseeType { get; set; }

    public string IsSubscribed { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNNotificationTopic GNNotificationTopic { get; set; }

    public virtual GNContact GNContact { get; set; }

}

}
