
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNNotificationTopic
{

    public GNNotificationTopic()
    {

        this.GNNotificationTopicSubscribers = new HashSet<GNNotificationTopicSubscriber>();

        this.GNNotificationLogs = new HashSet<GNNotificationLog>();

        this.GNNotificationTopicAddressees = new HashSet<GNNotificationTopicAddressee>();

    }


    public int Id { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Sender { get; set; }

    public string Format { get; set; }

    public string Priority { get; set; }

    public string Subject { get; set; }

    public string Message { get; set; }

    public string MessageTemplatePath { get; set; }

    public string IsSubscriptionOptional { get; set; }

    public string NotifyObjectCreator { get; set; }

    public string SendingCondition { get; set; }

    public string Status { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNNotificationTopicSubscriber> GNNotificationTopicSubscribers { get; set; }

    public virtual ICollection<GNNotificationLog> GNNotificationLogs { get; set; }

    public virtual ICollection<GNNotificationTopicAddressee> GNNotificationTopicAddressees { get; set; }

}

}
