
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNNotificationSuppressionList
{

    public long Id { get; set; }

    public string Email { get; set; }

    public System.DateTime CreateDateTime { get; set; }

    public string Category { get; set; }

    public string Type { get; set; }

    public string Subtype { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> NotifiedAdminOn { get; set; }

    public string AdminNotes { get; set; }

}

}
