
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNOrganization
{

    public GNOrganization()
    {

        this.UTCOffsetDescription = "";

        this.Contacts = new HashSet<GNContact>();

        this.Teams = new HashSet<GNTeam>();

        this.Samples = new HashSet<GNSample>();

        this.GNTemplates = new HashSet<GNTemplate>();

        this.GNBillingAccounts = new HashSet<GNBillingAccount>();

        this.GNSequencerJobs = new HashSet<GNSequencerJob>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public Nullable<System.Guid> GNContactId { get; set; }

    public System.Guid AWSConfigId { get; set; }

    public string UTCOffset { get; set; }

    public string UTCOffsetDescription { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public Nullable<int> GNSettingsTemplateId { get; set; }

    public string Repository { get; set; }



    public virtual ICollection<GNContact> Contacts { get; set; }

    public virtual ICollection<GNTeam> Teams { get; set; }

    public virtual ICollection<GNSample> Samples { get; set; }

    public virtual GNContact OrgMainContact { get; set; }

    public virtual GNAccount Account { get; set; }

    public virtual AWSConfig AWSConfig { get; set; }

    public virtual GNSettingsTemplate GNSettingsTemplate { get; set; }

    public virtual ICollection<GNTemplate> GNTemplates { get; set; }

    public virtual ICollection<GNBillingAccount> GNBillingAccounts { get; set; }

    public virtual ICollection<GNSequencerJob> GNSequencerJobs { get; set; }

}

}
