
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNPayment
{

    public GNPayment()
    {

        this.Invoices = new HashSet<GNInvoice>();

    }


    public System.Guid Id { get; set; }

    public double TotalAmount { get; set; }

    public System.DateTime PaymentDate { get; set; }

    public string ExternalTxnId { get; set; }

    public Nullable<System.Guid> GNPaymentMethodId { get; set; }

    public string Status { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNPaymentMethod PaymentMethod { get; set; }

    public virtual ICollection<GNInvoice> Invoices { get; set; }

}

}
