
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNProject
{

    public GNProject()
    {

        this.Teams = new HashSet<GNTeam>();

        this.AnalysisRequests = new HashSet<GNAnalysisRequest>();

        this.GNTransactions = new HashSet<GNTransaction>();

        this.GNBillingTransactions = new HashSet<GNBillingTransaction>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNContact ProjectLead { get; set; }

    public virtual ICollection<GNTeam> Teams { get; set; }

    public virtual ICollection<GNAnalysisRequest> AnalysisRequests { get; set; }

    public virtual ICollection<GNTransaction> GNTransactions { get; set; }

    public virtual ICollection<GNBillingTransaction> GNBillingTransactions { get; set; }

    public virtual GNSequencerJob GNSequencerJob { get; set; }

}

}
