
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNProduct
{

    public GNProduct()
    {

        this.AccountProductSubscriptions = new HashSet<GNAccountProductSubscription>();

        this.Transactions = new HashSet<GNTransaction>();

        this.GNBillingTransactions = new HashSet<GNBillingTransaction>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int GNProductTypeId { get; set; }

    public int SubscribeFrequency { get; set; }

    public double Cost { get; set; }

    public double Price { get; set; }

    public double MinRangeValue { get; set; }

    public double MaxRangeValue { get; set; }

    public string ValueUnits { get; set; }

    public int GNAccountTypeId { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNProductType ProductType { get; set; }

    public virtual ICollection<GNAccountProductSubscription> AccountProductSubscriptions { get; set; }

    public virtual ICollection<GNTransaction> Transactions { get; set; }

    public virtual GNAccountType AccountType { get; set; }

    public virtual ICollection<GNBillingTransaction> GNBillingTransactions { get; set; }

}

}
