
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNPurchaseOrder
{

    public GNPurchaseOrder()
    {

        this.PurchaseOrderInvoices = new HashSet<GNPurchaseOrderGNInvoice>();

        this.GNSharedPurchaseOrderOrganizations = new HashSet<GNSharedPurchaseOrderOrganization>();

    }


    public System.Guid Id { get; set; }

    public string ExternalPONum { get; set; }

    public double Total { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public System.Guid GNAccountId { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNAccount Account { get; set; }

    public virtual ICollection<GNPurchaseOrderGNInvoice> PurchaseOrderInvoices { get; set; }

    public virtual ICollection<GNSharedPurchaseOrderOrganization> GNSharedPurchaseOrderOrganizations { get; set; }

}

}
