
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNSampleStatus
{

    public GNSampleStatus()
    {

        this.SampleName = "SECONDARY";

    }


    public System.Guid Id { get; set; }

    public Nullable<System.Guid> GNSampleId { get; set; }

    public string SampleName { get; set; }

    public string Repository { get; set; }

    public string Message { get; set; }

    public int PercentComplete { get; set; }

    public bool IsError { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNSample GNSample { get; set; }

}

}
