
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNSampleRelationship
{

    public int Id { get; set; }

    public System.Guid GNLeftSampleId { get; set; }

    public System.Guid GNRightSampleId { get; set; }

    public int GNSampleRelationshipTypeId { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNSample GNLeftSample { get; set; }

    public virtual GNSample GNRightSample { get; set; }

    public virtual GNSampleRelationshipType GNSampleRelationshipType { get; set; }

}

}
