
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNSampleQualifier
{

    public GNSampleQualifier()
    {

        this.GNSamples = new HashSet<GNSample>();

    }


    public string Code { get; set; }

    public string Name { get; set; }

    public string GNSampleQualifierGroupCode { get; set; }

    public System.Guid CreatedBy { get; set; }

    public System.DateTime CreateDateTime { get; set; }



    public virtual GNSampleQualifierGroup GNSampleQualifierGroup { get; set; }

    public virtual ICollection<GNSample> GNSamples { get; set; }

}

}
