
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNSample
{

    public GNSample()
    {

        this.CloudFiles = new HashSet<GNCloudFile>();

        this.GNSampleLeftRelationships = new HashSet<GNSampleRelationship>();

        this.GNSampleRightRelationships = new HashSet<GNSampleRelationship>();

        this.GNAnalysisRequestGNSamples = new HashSet<GNAnalysisRequestGNSample>();

        this.GNAnalysisRequestGroups = new HashSet<GNAnalysisRequestGroup>();

        this.GNSampleStatus = new HashSet<GNSampleStatus>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public bool IsReady { get; set; }

    public bool IsPairEnded { get; set; }

    public string Gender { get; set; }

    public System.Guid GNOrganizationId { get; set; }

    public int GNSampleTypeId { get; set; }

    public string GNSampleQualifierCode { get; set; }

    public string Tags { get; set; }

    public string GNReplicateCode { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNCloudFile> CloudFiles { get; set; }

    public virtual GNOrganization Organization { get; set; }

    public virtual GNSampleType SampleType { get; set; }

    public virtual ICollection<GNSampleRelationship> GNSampleLeftRelationships { get; set; }

    public virtual ICollection<GNSampleRelationship> GNSampleRightRelationships { get; set; }

    public virtual ICollection<GNAnalysisRequestGNSample> GNAnalysisRequestGNSamples { get; set; }

    public virtual GNSampleQualifier GNSampleQualifier { get; set; }

    public virtual ICollection<GNAnalysisRequestGroup> GNAnalysisRequestGroups { get; set; }

    public virtual ICollection<GNSampleStatus> GNSampleStatus { get; set; }

    public virtual GNNewSampleBatchSamples GNNewSampleBatchSample { get; set; }

    public virtual GNReplicate GNReplicate { get; set; }

}

}
