
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNSampleRelationshipType
{

    public GNSampleRelationshipType()
    {

        this.GNSampleRelationships = new HashSet<GNSampleRelationship>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public int MaxRelationships { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNSampleRelationship> GNSampleRelationships { get; set; }

}

}
