
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNSettingsTemplateField
{

    public GNSettingsTemplateField()
    {

        this.GNSettingsTemplateConfigs = new HashSet<GNSettingsTemplateConfig>();

    }


    public string Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string ConfigType { get; set; }

    public string Description { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual ICollection<GNSettingsTemplateConfig> GNSettingsTemplateConfigs { get; set; }

}

}
