
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNSequencerJob
{

    public GNSequencerJob()
    {

        this.GNNewSampleBatches = new HashSet<GNNewSampleBatch>();

    }


    public System.Guid Id { get; set; }

    public System.Guid GNOrganizationId { get; set; }

    public string Project { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNOrganization GNOrganization { get; set; }

    public virtual ICollection<GNNewSampleBatch> GNNewSampleBatches { get; set; }

    public virtual GNProject GNProject { get; set; }

}

}
