
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNSharedPurchaseOrderOrganization
{

    public System.Guid Id { get; set; }

    public double AmountBilledOnInvoice { get; set; }

    public System.Guid GNPurchaseOrderId { get; set; }

    public System.Guid GNInvoiceId { get; set; }

    public string Notes { get; set; }

    public System.Guid CreatedBy { get; set; }

    public System.DateTime CreateDateTime { get; set; }



    public virtual GNInvoice GNInvoice { get; set; }

    public virtual GNPurchaseOrder GNPurchaseOrder { get; set; }

}

}
