
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GenomeNext.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class GNTeam
{

    public GNTeam()
    {

        this.TeamMembers = new HashSet<GNTeamMember>();

        this.Projects = new HashSet<GNProject>();

        this.GNTransactions = new HashSet<GNTransaction>();

        this.GNBillingTransactions = new HashSet<GNBillingTransaction>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public System.Guid OrganizationId { get; set; }

    public System.Guid GNContactId { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }



    public virtual GNContact TeamLead { get; set; }

    public virtual ICollection<GNTeamMember> TeamMembers { get; set; }

    public virtual GNOrganization Organization { get; set; }

    public virtual ICollection<GNProject> Projects { get; set; }

    public virtual ICollection<GNTransaction> GNTransactions { get; set; }

    public virtual ICollection<GNBillingTransaction> GNBillingTransactions { get; set; }

}

}
